//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class chofer
    {
        public int Chofer_ID { get; set; }
        public int Persona_ID { get; set; }
        public int Empresa_pertenece_ID { get; set; }
        public string Comentarios { get; set; }
    }
}
