//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_preferencias_cliente
    {
        public int Cliente_ID { get; set; }
        public int Cliente_Preferencias_cliente_ID { get; set; }
    }
}
