//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int Cliente_ID { get; set; }
        public int Empresa_ID { get; set; }
        public int Contacto_dueno_ID { get; set; }
        public int Contacto_encargado_lena_ID { get; set; }
        public int Contacto_encargado_pagos_ID { get; set; }
        public int Contacto_supervisor_lena_ID { get; set; }
        public int Contacto_nuestro_ID { get; set; }
        public int Forma_de_pago_ID { get; set; }
        public string Periodos_liquidacion { get; set; }
        public string Fechas_pago { get; set; }
        public string Comentarios { get; set; }
    }
}
