//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadrilla_descarga
    {
        public int Cuadrilla_descarga_ID { get; set; }
        public int Empresa_ID { get; set; }
        public string Comentarios { get; set; }
    }
}
