//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class empresa
    {
        public int Empresa_ID { get; set; }
        [Required]
        public string Nombre_fantasia { get; set; }
        public string Nombre_real { get; set; }
        public string RUT { get; set; }
        public int Contacto_medio_1_ID { get; set; }
        public int Contacto_medio_2_ID { get; set; }
        public int Contacto_persona_1_ID { get; set; }
        public int Contacto_persona_2_ID { get; set; }
        public int Banco_ID { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Comentarios { get; set; }
    }
}
