//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class persona
    {
        public int Persona_ID { get; set; }
        [Required]
        public string Apellidos { get; set; }
        [Required]
        public string Nombres { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public string CI { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Comentarios { get; set; }
    }
}
