//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class camion
    {
        public int Camion_ID { get; set; }
        public string Matricula_camion { get; set; }
        public string Matricula_zorra { get; set; }
        public int Numero_ejes { get; set; }
        public decimal Peso_Tara_origen { get; set; }
        public decimal Peso_Tara_destino { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Comentarios { get; set; }
        public decimal Peso_Neto { get; set; }
    }
}
