//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencias_cliente
    {
        public int Preferencias_cliente_ID { get; set; }
        public int Tipo_lena_ID { get; set; }
        public decimal Largo_lena { get; set; }
        public decimal Diametro_lena { get; set; }
        public int Lena_tipo_1_ID { get; set; }
        public int Lena_tipo_2_ID { get; set; }
        public string Comentarios { get; set; }
    }
}
