//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int Cliente_ID { get; set; }
        public string Dueno_nombre { get; set; }
        public string Dueno_contacto { get; set; }
        public string Encargado_lena_nombre { get; set; }
        public string Encargado_lena_contacto { get; set; }
        public string Encargado_pagos_nombre { get; set; }
        public string Encargado_pagos_contacto { get; set; }
        public string Supervisor_lena_nombre { get; set; }
        public string Supervisor_lena_contacto { get; set; }
        public int Contacto_nuestro_ID { get; set; }
        public int Forma_de_pago_ID { get; set; }
        public string Periodos_liquidacion { get; set; }
        public string Fechas_pago { get; set; }
        public string Nombre_fantasia { get; set; }
        public string Nombre_real { get; set; }
        public string RUT { get; set; }
        public string Direccion { get; set; }
        public string Telefono_1 { get; set; }
        public string Telefono_2 { get; set; }
        public string Email { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Comentarios { get; set; }
    }
}
