//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_pagos
    {
        public int Cliente_pagos_ID { get; set; }
        public int Cliente_ID { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public System.DateTime Fecha_pago { get; set; }
        public int Forma_de_pago_ID { get; set; }
        public decimal Monto { get; set; }
        public string Comentarios { get; set; }
    }
}
