//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class interno
    {
        public int Interno_ID { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public string CI { get; set; }
        public System.DateTime Fecha_ingreso { get; set; }
        public System.DateTime Fecha_egreso { get; set; }
        public string Cargo { get; set; }
        public string Comentarios { get; set; }
    }
}
