//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesada
    {
        public int pesada_ID { get; set; }
        public string Lugar { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre_balanza { get; set; }
        public decimal Peso_bruto { get; set; }
        public decimal Peso_neto { get; set; }
        public string Comentarios { get; set; }
    }
}
