//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2.Pages {
    
    
    public partial class Datos {
        
        /// <summary>
        /// Clientes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Clientes Clientes;
        
        /// <summary>
        /// Proveedores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Proveedores Proveedores;
        
        /// <summary>
        /// Cuadrillas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Cuadrillas Cuadrillas;
        
        /// <summary>
        /// Camiones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.Pages.Camiones1 Camiones;
        
        /// <summary>
        /// Choferes2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Choferes2 Choferes2;
        
        /// <summary>
        /// Internos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Internos Internos;
    }
}
