//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonisoft_2.Pages {
    
    
    public partial class Datos_configuracion {
        
        /// <summary>
        /// Tipos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Internos Tipos;
        
        /// <summary>
        /// Mercaderias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Internos Mercaderias;
        
        /// <summary>
        /// Formas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bonisoft_2.User_Controls.Internos Formas;
    }
}
